apiVersion: v1
kind: ConfigMap
metadata:
  name: betterfly2-config
  namespace: betterfly2
data:
  LOG_LEVEL: debug
  REDIS_ADDR: redis:6379
  KAFKA_BROKER: kafka:9092
  KAFKA_STORAGE_TOPIC: storage-service
  KAFKA_CONSUMER_GROUP: storage-service-group
  AUTH_RPC_ADDR: auth-service:50051
  HTTP_PORT: "8081"
  RUSTFS_REGION: cn-east-1
  RUSTFS_ENDPOINT_URL: http://rustfs:9000
  RUSTFS_EXTERNAL_ENDPOINT_URL: ""
  RUSTFS_EXTERNAL_PORT: "9000"
  RUSTFS_BUCKET: betterfly-files
  REGION_ID: local
  CALL_RING_TIMEOUT_SECONDS: "45"
  CALL_ACTIVE_TTL_SECONDS: "21600"
  TURN_CREDENTIAL_TTL_SECONDS: "3600"
  TURN_PUBLIC_HOST: localhost
  TURN_REALM: betterfly.local
  TURN_EXTERNAL_IP: 127.0.0.1
  APNS_KEY_ID: C6D5695Q4Y
  APNS_TEAM_ID: 8R5Q4A3RC7
  APNS_BUNDLE_ID: com.Voltline.Betterfly2
