apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - redis.yaml
  - kafka.yaml
  - rustfs.yaml
  - auth-service.yaml
  - data-forwarding.yaml
  - storage-service.yaml
  - friend-service.yaml
  - call-service.yaml
  - push-service.yaml
  - coturn.yaml
  - ingress.yaml
